[package]
name = "rust_midi_patcher"
version = "0.1.0"
authors = ["shybyte <ein@volloeko.de>"]

[dependencies]
portmidi = "^0.2.4"
chan-signal = "0.2.0"
chan = "0.1.19"
piston_window = "0.64.0"
risp = "0.2.0"
